<script>
  let trustless = "./images/trustless.svg";
  let member = "./images/member.svg";
  let opensource = "./images/opensource.svg";

  function toggleFooterSection(e) {
    const list = e.target.parentElement.parentElement.querySelector("article");
    if (list.classList.contains("h-0")) {
      list.classList.remove("h-0");
    } else {
      list.classList.add("h-0");
    }
  }
</script>

<section class="bg-gray-700">
  <div class="max-w-screen-xl mx-auto md:px-4 md:pt-10 md:pb-5">
    <div class="flex items-center flex-col">
      <h1
        class="brand-green font-mono sm:text-lg md:text-xl lg:text-2xl my-auto
        mx-auto md:mx-48 mb-5">
        PanDAO is a Insurance Co-op
      </h1>

      <p class="text-white text-lg mb-20 text-center">
        A decentralized autonomous organization summoned to manage pools of
        liquidity. These pools are used to provide every day users insurance
        coverage for their assets.
      </p>
    </div>

    <div
      class="border-none px-4 flex flex-row my-5 justify-between items-center
      w-full">
      <div class="mr-5">
        <div class="flex justify-center">
          <img class="w-20 mt-0" src={trustless} alt="trustless" />
        </div>

        <h1 class="brand-green text-center mb-5">Trustless</h1>
        <p class="text-white">
          Decision making is handled by consensus vote of all members, and you
          are always in control of your share of the DAO.
        </p>
      </div>

      <div class="mr-5">
        <div class="flex justify-center">
          <img class="w-20 lg:mt-6" src={member} alt="trustless" />
        </div>
        <h1 class="brand-green text-center mb-5">Member Owned</h1>

        <p class="text-white">
          All members are owners and afforded the rights, responsibilities, and
          claim to revenue generated by the DAO.
        </p>
      </div>

      <div>
        <div class="flex justify-center">
          <img class="w-20 mt-0" src={opensource} alt="trustless" />
        </div>
        <h1 class="brand-green text-center mb-5">Opensource Organization</h1>
        <p class="text-white">
          PanDAO is opensource to the core. From code to decision making and
          finances, everything is on the blockchain and completely open for
          anyone to see at any time.
        </p>
      </div>
    </div>
  </div>
</section>
