<script>
  function toggleFooterSection(e) {
    const list = e.target.parentElement.parentElement.querySelector("article");
    if (list.classList.contains("h-0")) {
      list.classList.remove("h-0");
    } else {
      list.classList.add("h-0");
    }
  }
</script>

<section class="bg-gray-700">
  <div class="max-w-screen-xl mx-auto md:px-4 md:pt-10 md:pb-5">
    <div class="flex items-center flex-col">
      <h1
        class="brand-green font-mono sm:text-lg md:text-xl lg:text-2xl my-auto
        mx-auto md:mx-48">
        PanDAO is a Insurance Co-op
      </h1>

      <p class="text-white text-lg mb-20 text-center">
        PanDAO is a decentralized autonomous organization summoned to manage
        pools of liquidity. These pools are used to provide every day users
        insurance coverage for their digital assets.
      </p>
    </div>

    <div
      class="border-none px-4 flex flex-row my-5 justify-between items-center
      w-full">
      <div class="mr-5">
        <h1 class="brand-green text-center">Trustless</h1>
        <p class="text-white">
          Network decisions are voted on by all participating members and the
          DAO can never take ownership of your funds within the network.
        </p>
      </div>

      <div class="mr-5">
        <h1 class="brand-green text-center">Member Owned</h1>
        <p class="text-white">
          All members are owners and afforded the rights, responsibilities, and
          claim to revenue generated by the DAO.
        </p>
      </div>

      <div>
        <h1 class="brand-green text-center">Opensource Organization</h1>
        <p class="text-white">
          PanDAO is opensource to the core. From code to decision making and
          finances, everything is on the blockchain and completely open for
          anyone to see at any time.
        </p>
      </div>
    </div>
  </div>
</section>
